.container-build-tmpl:
  stage: containers
  image: docker:stable
  tags:
    - container-builder
  services:
    - docker:dind
  before_script:
    - apk add make
    - docker info
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
  script:
    - make -C automation/build PUSH=1 REGISTRY=${XEN_REGISTRY} ${CONTAINER/:/\/}
  after_script:
    - docker logout

.container-schedule-tmpl:
  extends:
    - .container-build-tmpl
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - when: manual

container-archlinux-current:
  extends:
    - .container-schedule-tmpl
  variables:
    CONTAINER: "archlinux:current"

container-opensuse-tumbleweed-x86_64:
  extends:
    - .container-schedule-tmpl
  variables:
    CONTAINER: "opensuse:tumbleweed-x86_64"

container-single:
  extends:
    - .container-build-tmpl
  when:
    manual

container-all:
  extends:
    - .container-build-tmpl
  when:
    manual
  variables:
    CONTAINER: "all"
